### ISSUE TITLE
Missing tracks when ripping Crash of the Titans

### ISSUE THREAD

**Issue by FrankyBuster** [MCJack123/UnkrawerterGBA#1]
For whatever reason when scanning this game, Unkrawerter skips both Bandicoot Beach and the pause theme, even when lowering the search threshold.

Going by my research, those songs should be stored after n gin(rock song) and the title theme(brassy song) respectively.

**Comment by MCJack123** [comment]
Turns out the issue was that BPM values >200 were getting filtered out. Since both songs have BPMs over 200, they were not being detected. This is fixed in 3.1.
