### ISSUE TITLE
Support for Harry Potter and the Goblet of Fire

### ISSUE THREAD

**Issue by Bonboon229** [MCJack123/UnkrawerterGBA#3]
Unkrawerter detects the songlist of the rom in question, but does not find the required offsets to rip the tracks. I do suspect the game uses the Krawall engine.

**Comment by MCJack123** [comment]
Harry Potter and the Goblet of Fire uses the GAX engine:
```
00758EE4    GAX Sound Engine 3.05A (Aug 16 2004) © Shin'en Multimedia. Code: B.Wodok
```
